### ISSUE TITLE
handle 502 errors

### ISSUE THREAD

**Issue by treznick** [ContinuityControl/fdic#4]
Found this little gem when trying to search for around 5000 banks by name
```
/home/treznick/.rvm/gems/ruby-2.2.3@global/gems/json-1.8.3/lib/json/common.rb:155:in `parse': 795: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> (JSON::ParserError)
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The request could not be processed.  An invalid response was received by the proxy or gateway server.</p>
</body></html>
'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/json-1.8.3/lib/json/common.rb:334:in `load'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/httparty-0.13.5/lib/httparty/parser.rb:116:in `json'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/httparty-0.13.5/lib/httparty/parser.rb:136:in `parse_supported_format'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/httparty-0.13.5/lib/httparty/parser.rb:103:in `parse'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/httparty-0.13.5/lib/httparty/parser.rb:67:in `call'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/httparty-0.13.5/lib/httparty/request.rb:309:in `parse_response'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/httparty-0.13.5/lib/httparty/request.rb:279:in `block in handle_response'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/httparty-0.13.5/lib/httparty/response.rb:23:in `call'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/httparty-0.13.5/lib/httparty/response.rb:23:in `parsed_response'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/httparty-0.13.5/lib/httparty/response.rb:66:in `method_missing'
        from /home/treznick/.rvm/gems/ruby-2.2.3@global/gems/fdic-0.6.0/lib/fdic/bank_find.rb:14:in `find_bank'
        from org_parser.rb:18:in `block (2 levels) in <main>'
        from /home/treznick/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/csv.rb:1739:in `each'
        from /home/treznick/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/csv.rb:1122:in `block in foreach'
        from /home/treznick/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/csv.rb:1273:in `open'
        from /home/treznick/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/csv.rb:1121:in `foreach'
        from org_parser.rb:15:in `block in <main>'
        from /home/treznick/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/csv.rb:1273:in `open'
        from org_parser.rb:13:in `<main>'
```

Here's the bit of code I used to eventually hit this:
```ruby
require 'fdic'
require 'csv'

def results_first_match(results)
  if results.length == 1
    institution = results.first.find_institution!
    [institution.address, institution.city, institution.state, institution.zip, institution.certificate_number, institution.legal_name]
  else
    []
  end
end

CSV.open("fdic_org_match_by_name.csv", "w") do |csv|
  csv << %w(csv_id name charter_number num_matches first_match_address first_match_city first_match_state first_match_zip first_match_certificate_number fdic_name)
  CSV.foreach("orgs_with_charter_details.csv", headers: true, header_converters: :symbol) do |org|

    puts org[:name]
    results = FDIC::BankFind.find_bank(org[:name])
    row = [org[:id], org[:name], org[:charter_number], results.count]
    row += results_first_match(results)
    csv << row
  end
end
```

`orgs_with_charter_details` has the headers `id`,`name`,`charter_number`, and `charter_class`

the failing record, `TrustUS FCU TX` was the ~3400 th record. the script had been running for several hours.

**Comment by treznick** [comment]
I'll PR a fix to return another error object on 502
